# Generated by Django 4.0.5 on 2022-06-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_create_at_article_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Автор'),
        ),
    ]
